---
description: "Big event test"
threadCount: 8
summary: ./logs/summary.log
timeouts:
  logFile: ./logs/timeouts.log
  samplingPeriod: 1000
profile:
  - start: 0
    scenarios:
      - type: CallCenterEmployee
        count: 0
      - type: ClassicUser
        count: 500
      - type: MalfunctioningCellPhone
        count: 0
      - type: TravellingManager
        count: 0
  - start: 180000
    scenarios:
      - type: CallCenterEmployee
        count: 0
      - type: ClassicUser
        count: 300
      - type: MalfunctioningCellPhone
        count: 0
      - type: TravellingManager
        count: 0
  - start: 360000
    scenarios:
      - type: CallCenterEmployee
        count: 0
      - type: ClassicUser
        count: 200
      - type: MalfunctioningCellPhone
        count: 0
      - type: TravellingManager
        count: 0
  - start: 540000
    scenarios:
      - type: CallCenterEmployee
        count: 0
      - type: ClassicUser
        count: 150
      - type: MalfunctioningCellPhone
        count: 0
      - type: TravellingManager
        count: 0
  - start: 720000
    scenarios:
      - type: CallCenterEmployee
        count: 0
      - type: ClassicUser
        count: 150
      - type: MalfunctioningCellPhone
        count: 0
      - type: TravellingManager
        count: 0
  - start: 900000
    scenarios:
      - type: CallCenterEmployee
        count: 0
      - type: ClassicUser
        count: 100
      - type: MalfunctioningCellPhone
        count: 0
      - type: TravellingManager
        count: 0
  - start: 1080000
    scenarios:
      - type: CallCenterEmployee
        count: 0
      - type: ClassicUser
        count: 100
      - type: MalfunctioningCellPhone
        count: 0
      - type: TravellingManager
        count: 0
  - start: 1260000
    scenarios:
      - type: CallCenterEmployee
        count: 0
      - type: ClassicUser
        count: 80
      - type: MalfunctioningCellPhone
        count: 0
      - type: TravellingManager
        count: 0
  - start: 1440000
    scenarios:
      - type: CallCenterEmployee
        count: 0
      - type: ClassicUser
        count: 100
      - type: MalfunctioningCellPhone
        count: 0
      - type: TravellingManager
        count: 0
  - start: 1620000
    scenarios:
      - type: CallCenterEmployee
        count: 0
      - type: ClassicUser
        count: 130
      - type: MalfunctioningCellPhone
        count: 0
      - type: TravellingManager
        count: 0
  - start: 1800000
    scenarios:
      - type: CallCenterEmployee
        count: 0
      - type: ClassicUser
        count: 200
      - type: MalfunctioningCellPhone
        count: 0
      - type: TravellingManager
        count: 0
  - start: 1980000
    scenarios:
      - type: CallCenterEmployee
        count: 0
      - type: ClassicUser
        count: 350
      - type: MalfunctioningCellPhone
        count: 0
      - type: TravellingManager
        count: 0
  - start: 2160000
    scenarios:
      - type: CallCenterEmployee
        count: 0
      - type: ClassicUser
        count: 600
      - type: MalfunctioningCellPhone
        count: 0
      - type: TravellingManager
        count: 0
  - start: 2340000
    scenarios:
      - type: CallCenterEmployee
        count: 0
      - type: ClassicUser
        count: 1000
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 0
  - start: 2520000
    scenarios:
      - type: CallCenterEmployee
        count: 0
      - type: ClassicUser
        count: 2000
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 0
  - start: 2700000
    scenarios:
      - type: CallCenterEmployee
        count: 2
      - type: ClassicUser
        count: 3000
      - type: MalfunctioningCellPhone
        count: 2
      - type: TravellingManager
        count: 1
  - start: 2880000
    scenarios:
      - type: CallCenterEmployee
        count: 10
      - type: ClassicUser
        count: 5000
      - type: MalfunctioningCellPhone
        count: 5
      - type: TravellingManager
        count: 3
  - start: 3060000
    scenarios:
      - type: CallCenterEmployee
        count: 20
      - type: ClassicUser
        count: 7000
      - type: MalfunctioningCellPhone
        count: 7
      - type: TravellingManager
        count: 5
  - start: 3240000
    scenarios:
      - type: CallCenterEmployee
        count: 50
      - type: ClassicUser
        count: 9000
      - type: MalfunctioningCellPhone
        count: 8
      - type: TravellingManager
        count: 10
  - start: 3420000
    scenarios:
      - type: CallCenterEmployee
        count: 50
      - type: ClassicUser
        count: 10000
      - type: MalfunctioningCellPhone
        count: 9
      - type: TravellingManager
        count: 20
  - start: 3600000
    scenarios:
      - type: CallCenterEmployee
        count: 50
      - type: ClassicUser
        count: 15000
      - type: MalfunctioningCellPhone
        count: 15
      - type: TravellingManager
        count: 30
  - start: 3780000
    scenarios:
      - type: CallCenterEmployee
        count: 50
      - type: ClassicUser
        count: 13000
      - type: MalfunctioningCellPhone
        count: 13
      - type: TravellingManager
        count: 50
  - start: 3960000
    scenarios:
      - type: CallCenterEmployee
        count: 50
      - type: ClassicUser
        count: 11500
      - type: MalfunctioningCellPhone
        count: 10
      - type: TravellingManager
        count: 50
  - start: 4140000
    scenarios:
      - type: CallCenterEmployee
        count: 50
      - type: ClassicUser
        count: 10500
      - type: MalfunctioningCellPhone
        count: 10
      - type: TravellingManager
        count: 50
  - start: 4320000
    scenarios:
      - type: CallCenterEmployee
        count: 30
      - type: ClassicUser
        count: 10000
      - type: MalfunctioningCellPhone
        count: 90
      - type: TravellingManager
        count: 50
  - start: 4500000
    scenarios:
      - type: CallCenterEmployee
        count: 20
      - type: ClassicUser
        count: 10000
      - type: MalfunctioningCellPhone
        count: 90
      - type: TravellingManager
        count: 40
  - start: 4680000
    scenarios:
      - type: CallCenterEmployee
        count: 60
      - type: ClassicUser
        count: 10000
      - type: MalfunctioningCellPhone
        count: 10
      - type: TravellingManager
        count: 50
  - start: 4860000
    scenarios:
      - type: CallCenterEmployee
        count: 70
      - type: ClassicUser
        count: 10000
      - type: MalfunctioningCellPhone
        count: 10
      - type: TravellingManager
        count: 60
  - start: 5040000
    scenarios:
      - type: CallCenterEmployee
        count: 80
      - type: ClassicUser
        count: 10000
      - type: MalfunctioningCellPhone
        count: 10
      - type: TravellingManager
        count: 60
  - start: 5220000
    scenarios:
      - type: CallCenterEmployee
        count: 80
      - type: ClassicUser
        count: 10000
      - type: MalfunctioningCellPhone
        count: 10
      - type: TravellingManager
        count: 70
  - start: 5400000
    scenarios:
      - type: CallCenterEmployee
        count: 80
      - type: ClassicUser
        count: 10000
      - type: MalfunctioningCellPhone
        count: 9
      - type: TravellingManager
        count: 60
  - start: 5580000
    scenarios:
      - type: CallCenterEmployee
        count: 70
      - type: ClassicUser
        count: 9500
      - type: MalfunctioningCellPhone
        count: 8
      - type: TravellingManager
        count: 50
  - start: 5760000
    scenarios:
      - type: CallCenterEmployee
        count: 50
      - type: ClassicUser
        count: 9500
      - type: MalfunctioningCellPhone
        count: 5
      - type: TravellingManager
        count: 50
  - start: 5940000
    scenarios:
      - type: CallCenterEmployee
        count: 30
      - type: ClassicUser
        count: 9000
      - type: MalfunctioningCellPhone
        count: 5
      - type: TravellingManager
        count: 30
  - start: 6120000
    scenarios:
      - type: CallCenterEmployee
        count: 10
      - type: ClassicUser
        count: 8000
      - type: MalfunctioningCellPhone
        count: 5
      - type: TravellingManager
        count: 20
  - start: 6300000
    scenarios:
      - type: CallCenterEmployee
        count: 5
      - type: ClassicUser
        count: 7500
      - type: MalfunctioningCellPhone
        count: 5
      - type: TravellingManager
        count: 10
  - start: 6480000
    scenarios:
      - type: CallCenterEmployee
        count: 0
      - type: ClassicUser
        count: 12000
      - type: MalfunctioningCellPhone
        count: 10
      - type: TravellingManager
        count: 5
  - start: 6660000
    scenarios:
      - type: CallCenterEmployee
        count: 0
      - type: ClassicUser
        count: 11000
      - type: MalfunctioningCellPhone
        count: 10
      - type: TravellingManager
        count: 3
  - start: 6840000
    scenarios:
      - type: CallCenterEmployee
        count: 0
      - type: ClassicUser
        count: 10000
      - type: MalfunctioningCellPhone
        count: 7
      - type: TravellingManager
        count: 2
  - start: 7020000
    scenarios:
      - type: CallCenterEmployee
        count: 0
      - type: ClassicUser
        count: 8000
      - type: MalfunctioningCellPhone
        count: 5
      - type: TravellingManager
        count: 1
  - start: 7200000
    scenarios:
      - type: CallCenterEmployee
        count: 0
      - type: ClassicUser
        count: 5000
      - type: MalfunctioningCellPhone
        count: 2
      - type: TravellingManager
        count: 1
  - start: 7380000
    scenarios:
      - type: CallCenterEmployee
        count: 0
      - type: ClassicUser
        count: 4000
      - type: MalfunctioningCellPhone
        count: 2
      - type: TravellingManager
        count: 1
  - start: 7560000
    scenarios:
      - type: CallCenterEmployee
        count: 0
      - type: ClassicUser
        count: 3000
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 0
  - start: 7740000
    scenarios:
      - type: CallCenterEmployee
        count: 0
      - type: ClassicUser
        count: 2500
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 0
  - start: 7920000
    scenarios:
      - type: CallCenterEmployee
        count: 0
      - type: ClassicUser
        count: 1500
      - type: MalfunctioningCellPhone
        count: 0
      - type: TravellingManager
        count: 0
  - start: 8100000
    scenarios:
      - type: CallCenterEmployee
        count: 0
      - type: ClassicUser
        count: 1000
      - type: MalfunctioningCellPhone
        count: 0
      - type: TravellingManager
        count: 0
  - start: 8280000
    scenarios:
      - type: CallCenterEmployee
        count: 0
      - type: ClassicUser
        count: 800
      - type: MalfunctioningCellPhone
        count: 0
      - type: TravellingManager
        count: 0
  - start: 8460000
    scenarios:
      - type: CallCenterEmployee
        count: 0
      - type: ClassicUser
        count: 500
      - type: MalfunctioningCellPhone
        count: 0
      - type: TravellingManager
        count: 0
end: 8640000
