---
description: "Big event test"
threadCount: 8
summary: ./logs/summary.log
timeouts:
  logFile: ./logs/timeouts.log
  samplingPeriod: 1000
profile:
  - start: 0
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 180000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 360000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 540000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 720000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 900000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 1080000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 1260000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 1440000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 1620000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 1800000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 1980000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 2160000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 2340000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 2520000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 2700000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 2880000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 3060000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 3240000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 3420000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 3600000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 3780000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 3960000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 4140000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 4320000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 4500000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 4680000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 4860000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 5040000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 5220000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 5400000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 5580000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 5760000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 5940000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 6120000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 6300000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 6480000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 6660000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 6840000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 7020000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 7200000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 7380000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 7560000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 7740000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 7920000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 8100000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 8280000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
  - start: 8460000
    scenarios:
      - type: CallCenterEmployee
        count: 1
      - type: ClassicUser
        count: 1
      - type: MalfunctioningCellPhone
        count: 1
      - type: TravellingManager
        count: 1
end: 8640000
