---
description: "Big event test"
threadCount: 8
summary: ./logs/summary.log
statistics:
  logFile: ./logs/statistics.log
  samplingPeriod: 1000
profile:
  burstLimit: 50
  end: 8640
  flow:
    - start: 0
      scenarios:
        - type: CallCenterEmployee
          count: 0
        - type: ClassicUser
          count: 500
        - type: MalfunctioningCellPhone
          count: 0
        - type: TravellingManager
          count: 0
    - start: 180
      scenarios:
        - type: CallCenterEmployee
          count: 0
        - type: ClassicUser
          count: 300
        - type: MalfunctioningCellPhone
          count: 0
        - type: TravellingManager
          count: 0
    - start: 360
      scenarios:
        - type: CallCenterEmployee
          count: 0
        - type: ClassicUser
          count: 200
        - type: MalfunctioningCellPhone
          count: 0
        - type: TravellingManager
          count: 0
    - start: 540
      scenarios:
        - type: CallCenterEmployee
          count: 0
        - type: ClassicUser
          count: 150
        - type: MalfunctioningCellPhone
          count: 0
        - type: TravellingManager
          count: 0
    - start: 720
      scenarios:
        - type: CallCenterEmployee
          count: 0
        - type: ClassicUser
          count: 150
        - type: MalfunctioningCellPhone
          count: 0
        - type: TravellingManager
          count: 0
    - start: 900
      scenarios:
        - type: CallCenterEmployee
          count: 0
        - type: ClassicUser
          count: 100
        - type: MalfunctioningCellPhone
          count: 0
        - type: TravellingManager
          count: 0
    - start: 1080
      scenarios:
        - type: CallCenterEmployee
          count: 0
        - type: ClassicUser
          count: 100
        - type: MalfunctioningCellPhone
          count: 0
        - type: TravellingManager
          count: 0
    - start: 1260
      scenarios:
        - type: CallCenterEmployee
          count: 0
        - type: ClassicUser
          count: 80
        - type: MalfunctioningCellPhone
          count: 0
        - type: TravellingManager
          count: 0
    - start: 1440
      scenarios:
        - type: CallCenterEmployee
          count: 0
        - type: ClassicUser
          count: 100
        - type: MalfunctioningCellPhone
          count: 0
        - type: TravellingManager
          count: 0
    - start: 1620
      scenarios:
        - type: CallCenterEmployee
          count: 0
        - type: ClassicUser
          count: 130
        - type: MalfunctioningCellPhone
          count: 0
        - type: TravellingManager
          count: 0
    - start: 1800
      scenarios:
        - type: CallCenterEmployee
          count: 0
        - type: ClassicUser
          count: 200
        - type: MalfunctioningCellPhone
          count: 0
        - type: TravellingManager
          count: 0
    - start: 1980
      scenarios:
        - type: CallCenterEmployee
          count: 0
        - type: ClassicUser
          count: 350
        - type: MalfunctioningCellPhone
          count: 0
        - type: TravellingManager
          count: 0
    - start: 2160
      scenarios:
        - type: CallCenterEmployee
          count: 0
        - type: ClassicUser
          count: 600
        - type: MalfunctioningCellPhone
          count: 0
        - type: TravellingManager
          count: 0
    - start: 2340
      scenarios:
        - type: CallCenterEmployee
          count: 0
        - type: ClassicUser
          count: 1000
        - type: MalfunctioningCellPhone
          count: 1
        - type: TravellingManager
          count: 0
    - start: 2520
      scenarios:
        - type: CallCenterEmployee
          count: 0
        - type: ClassicUser
          count: 2000
        - type: MalfunctioningCellPhone
          count: 1
        - type: TravellingManager
          count: 0
    - start: 2700
      scenarios:
        - type: CallCenterEmployee
          count: 2
        - type: ClassicUser
          count: 3000
        - type: MalfunctioningCellPhone
          count: 2
        - type: TravellingManager
          count: 1
    - start: 2880
      scenarios:
        - type: CallCenterEmployee
          count: 10
        - type: ClassicUser
          count: 5000
        - type: MalfunctioningCellPhone
          count: 5
        - type: TravellingManager
          count: 3
    - start: 3060
      scenarios:
        - type: CallCenterEmployee
          count: 20
        - type: ClassicUser
          count: 7000
        - type: MalfunctioningCellPhone
          count: 7
        - type: TravellingManager
          count: 5
    - start: 3240
      scenarios:
        - type: CallCenterEmployee
          count: 50
        - type: ClassicUser
          count: 9000
        - type: MalfunctioningCellPhone
          count: 8
        - type: TravellingManager
          count: 10
    - start: 3420
      scenarios:
        - type: CallCenterEmployee
          count: 50
        - type: ClassicUser
          count: 10000
        - type: MalfunctioningCellPhone
          count: 9
        - type: TravellingManager
          count: 20
    - start: 3600
      scenarios:
        - type: CallCenterEmployee
          count: 50
        - type: ClassicUser
          count: 15000
        - type: MalfunctioningCellPhone
          count: 15
        - type: TravellingManager
          count: 30
    - start: 3780
      scenarios:
        - type: CallCenterEmployee
          count: 50
        - type: ClassicUser
          count: 13000
        - type: MalfunctioningCellPhone
          count: 13
        - type: TravellingManager
          count: 50
    - start: 3960
      scenarios:
        - type: CallCenterEmployee
          count: 50
        - type: ClassicUser
          count: 11500
        - type: MalfunctioningCellPhone
          count: 10
        - type: TravellingManager
          count: 50
    - start: 4140
      scenarios:
        - type: CallCenterEmployee
          count: 50
        - type: ClassicUser
          count: 10500
        - type: MalfunctioningCellPhone
          count: 10
        - type: TravellingManager
          count: 50
    - start: 4320
      scenarios:
        - type: CallCenterEmployee
          count: 30
        - type: ClassicUser
          count: 10000
        - type: MalfunctioningCellPhone
          count: 90
        - type: TravellingManager
          count: 50
    - start: 4500
      scenarios:
        - type: CallCenterEmployee
          count: 20
        - type: ClassicUser
          count: 10000
        - type: MalfunctioningCellPhone
          count: 90
        - type: TravellingManager
          count: 40
    - start: 4680
      scenarios:
        - type: CallCenterEmployee
          count: 60
        - type: ClassicUser
          count: 10000
        - type: MalfunctioningCellPhone
          count: 10
        - type: TravellingManager
          count: 50
    - start: 4860
      scenarios:
        - type: CallCenterEmployee
          count: 70
        - type: ClassicUser
          count: 10000
        - type: MalfunctioningCellPhone
          count: 10
        - type: TravellingManager
          count: 60
    - start: 5040
      scenarios:
        - type: CallCenterEmployee
          count: 80
        - type: ClassicUser
          count: 10000
        - type: MalfunctioningCellPhone
          count: 10
        - type: TravellingManager
          count: 60
    - start: 5220
      scenarios:
        - type: CallCenterEmployee
          count: 80
        - type: ClassicUser
          count: 10000
        - type: MalfunctioningCellPhone
          count: 10
        - type: TravellingManager
          count: 70
    - start: 5400
      scenarios:
        - type: CallCenterEmployee
          count: 80
        - type: ClassicUser
          count: 10000
        - type: MalfunctioningCellPhone
          count: 9
        - type: TravellingManager
          count: 60
    - start: 5580
      scenarios:
        - type: CallCenterEmployee
          count: 70
        - type: ClassicUser
          count: 9500
        - type: MalfunctioningCellPhone
          count: 8
        - type: TravellingManager
          count: 50
    - start: 5760
      scenarios:
        - type: CallCenterEmployee
          count: 50
        - type: ClassicUser
          count: 9500
        - type: MalfunctioningCellPhone
          count: 5
        - type: TravellingManager
          count: 50
    - start: 5940
      scenarios:
        - type: CallCenterEmployee
          count: 30
        - type: ClassicUser
          count: 9000
        - type: MalfunctioningCellPhone
          count: 5
        - type: TravellingManager
          count: 30
    - start: 6120
      scenarios:
        - type: CallCenterEmployee
          count: 10
        - type: ClassicUser
          count: 8000
        - type: MalfunctioningCellPhone
          count: 5
        - type: TravellingManager
          count: 20
    - start: 6300
      scenarios:
        - type: CallCenterEmployee
          count: 5
        - type: ClassicUser
          count: 7500
        - type: MalfunctioningCellPhone
          count: 5
        - type: TravellingManager
          count: 10
    - start: 6480
      scenarios:
        - type: CallCenterEmployee
          count: 0
        - type: ClassicUser
          count: 12000
        - type: MalfunctioningCellPhone
          count: 10
        - type: TravellingManager
          count: 5
    - start: 6660
      scenarios:
        - type: CallCenterEmployee
          count: 0
        - type: ClassicUser
          count: 11000
        - type: MalfunctioningCellPhone
          count: 10
        - type: TravellingManager
          count: 3
    - start: 6840
      scenarios:
        - type: CallCenterEmployee
          count: 0
        - type: ClassicUser
          count: 10000
        - type: MalfunctioningCellPhone
          count: 7
        - type: TravellingManager
          count: 2
    - start: 7020
      scenarios:
        - type: CallCenterEmployee
          count: 0
        - type: ClassicUser
          count: 8000
        - type: MalfunctioningCellPhone
          count: 5
        - type: TravellingManager
          count: 1
    - start: 7200
      scenarios:
        - type: CallCenterEmployee
          count: 0
        - type: ClassicUser
          count: 5000
        - type: MalfunctioningCellPhone
          count: 2
        - type: TravellingManager
          count: 1
    - start: 7380
      scenarios:
        - type: CallCenterEmployee
          count: 0
        - type: ClassicUser
          count: 4000
        - type: MalfunctioningCellPhone
          count: 2
        - type: TravellingManager
          count: 1
    - start: 7560
      scenarios:
        - type: CallCenterEmployee
          count: 0
        - type: ClassicUser
          count: 3000
        - type: MalfunctioningCellPhone
          count: 1
        - type: TravellingManager
          count: 0
    - start: 7740
      scenarios:
        - type: CallCenterEmployee
          count: 0
        - type: ClassicUser
          count: 2500
        - type: MalfunctioningCellPhone
          count: 1
        - type: TravellingManager
          count: 0
    - start: 7920
      scenarios:
        - type: CallCenterEmployee
          count: 0
        - type: ClassicUser
          count: 1500
        - type: MalfunctioningCellPhone
          count: 0
        - type: TravellingManager
          count: 0
    - start: 8100
      scenarios:
        - type: CallCenterEmployee
          count: 0
        - type: ClassicUser
          count: 1000
        - type: MalfunctioningCellPhone
          count: 0
        - type: TravellingManager
          count: 0
    - start: 8280
      scenarios:
        - type: CallCenterEmployee
          count: 0
        - type: ClassicUser
          count: 800
        - type: MalfunctioningCellPhone
          count: 0
        - type: TravellingManager
          count: 0
    - start: 8460
      scenarios:
        - type: CallCenterEmployee
          count: 0
        - type: ClassicUser
          count: 500
        - type: MalfunctioningCellPhone
          count: 0
        - type: TravellingManager
          count: 0
