---
description: "Call performance test"
threadCount: 8
summary: ./logs/summary.log
statistics:
  logFile: ./logs/statistics.log
  samplingPeriod: 1000
profile:
  - start: 0
    scenarios:
      - type: CallPerformance
        count: 150
  - start: 120
    scenarios:
      - type: CallPerformance
        count: 300
  - start: 240
    scenarios:
      - type: CallPerformance
        count: 450
  - start: 360
    scenarios:
      - type: CallPerformance
        count: 600
  - start: 480
    scenarios:
      - type: CallPerformance
        count: 750
  - start: 600
    scenarios:
      - type: CallPerformance
        count: 900
  - start: 720
    scenarios:
      - type: CallPerformance
        count: 1050
  - start: 840
    scenarios:
      - type: CallPerformance
        count: 1200
  - start: 960
    scenarios:
      - type: CallPerformance
        count: 1350
  - start: 1080
    scenarios:
      - type: CallPerformance
        count: 1500
  - start: 1200
    scenarios:
      - type: CallPerformance
        count: 1650
  - start: 1320
    scenarios:
      - type: CallPerformance
        count: 1800
  - start: 1440
    scenarios:
      - type: CallPerformance
        count: 1950
  - start: 1560
    scenarios:
      - type: CallPerformance
        count: 2100
  - start: 1680
    scenarios:
      - type: CallPerformance
        count: 2250
  - start: 1800
    scenarios:
      - type: CallPerformance
        count: 2400
  - start: 1920
    scenarios:
      - type: CallPerformance
        count: 2550
  - start: 2040
    scenarios:
      - type: CallPerformance
        count: 2700
  - start: 2160
    scenarios:
      - type: CallPerformance
        count: 2850
  - start: 2280
    scenarios:
      - type: CallPerformance
        count: 3000
  - start: 2400
    scenarios:
      - type: CallPerformance
        count: 3150
  - start: 2520
    scenarios:
      - type: CallPerformance
        count: 3300
  - start: 2640
    scenarios:
      - type: CallPerformance
        count: 3450
  - start: 2760
    scenarios:
      - type: CallPerformance
        count: 3600
  - start: 2880
    scenarios:
      - type: CallPerformance
        count: 3750
  - start: 3000
    scenarios:
      - type: CallPerformance
        count: 3900
  - start: 3120
    scenarios:
      - type: CallPerformance
        count: 4050
  - start: 3240
    scenarios:
      - type: CallPerformance
        count: 4200
  - start: 3360
    scenarios:
      - type: CallPerformance
        count: 4350
  - start: 3480
    scenarios:
      - type: CallPerformance
        count: 4500
  - start: 3600
    scenarios:
      - type: CallPerformance
        count: 4650
  - start: 3720
    scenarios:
      - type: CallPerformance
        count: 4800
  - start: 3840
    scenarios:
      - type: CallPerformance
        count: 4950
  - start: 3960
    scenarios:
      - type: CallPerformance
        count: 5100
  - start: 4080
    scenarios:
      - type: CallPerformance
        count: 5250
  - start: 4200
    scenarios:
      - type: CallPerformance
        count: 5400
  - start: 4320
    scenarios:
      - type: CallPerformance
        count: 5550
  - start: 4440
    scenarios:
      - type: CallPerformance
        count: 5700
  - start: 4560
    scenarios:
      - type: CallPerformance
        count: 5850
  - start: 4680
    scenarios:
      - type: CallPerformance
        count: 6000
  - start: 4800
    scenarios:
      - type: CallPerformance
        count: 6150
  - start: 4920
    scenarios:
      - type: CallPerformance
        count: 6300
  - start: 5040
    scenarios:
      - type: CallPerformance
        count: 6450
  - start: 5160
    scenarios:
      - type: CallPerformance
        count: 6600
  - start: 5280
    scenarios:
      - type: CallPerformance
        count: 6750
  - start: 5400
    scenarios:
      - type: CallPerformance
        count: 6900
  - start: 5520
    scenarios:
      - type: CallPerformance
        count: 7050
  - start: 5640
    scenarios:
      - type: CallPerformance
        count: 7200
  - start: 5760
    scenarios:
      - type: CallPerformance
        count: 7350
  - start: 5880
    scenarios:
      - type: CallPerformance
        count: 7500
  - start: 6000
    scenarios:
      - type: CallPerformance
        count: 7650
  - start: 6120
    scenarios:
      - type: CallPerformance
        count: 7800
  - start: 6240
    scenarios:
      - type: CallPerformance
        count: 7950
  - start: 6360
    scenarios:
      - type: CallPerformance
        count: 8100
  - start: 6480
    scenarios:
      - type: CallPerformance
        count: 8250
  - start: 6600
    scenarios:
      - type: CallPerformance
        count: 8400
  - start: 6720
    scenarios:
      - type: CallPerformance
        count: 8550
  - start: 6840
    scenarios:
      - type: CallPerformance
        count: 8700
  - start: 6960
    scenarios:
      - type: CallPerformance
        count: 8850
  - start: 7080
    scenarios:
      - type: CallPerformance
        count: 9000
  - start: 7200
    scenarios:
      - type: CallPerformance
        count: 9150
  - start: 7320
    scenarios:
      - type: CallPerformance
        count: 9300
  - start: 7440
    scenarios:
      - type: CallPerformance
        count: 9450
  - start: 7560
    scenarios:
      - type: CallPerformance
        count: 9600
  - start: 7680
    scenarios:
      - type: CallPerformance
        count: 9750
  - start: 7800
    scenarios:
      - type: CallPerformance
        count: 9900
  - start: 7920
    scenarios:
      - type: CallPerformance
        count: 10050
  - start: 8040
    scenarios:
      - type: CallPerformance
        count: 10200
  - start: 8160
    scenarios:
      - type: CallPerformance
        count: 10350
  - start: 8280
    scenarios:
      - type: CallPerformance
        count: 10500
  - start: 8400
    scenarios:
      - type: CallPerformance
        count: 10650
  - start: 8520
    scenarios:
      - type: CallPerformance
        count: 10800
end: 8640
