---
description: "Call performance test"
threadCount: 8
summary: ./logs/summary.log
statistics:
  logFile: ./logs/statistics.log
  samplingPeriod: 1000
profile:
  - start: 0
    scenarios:
      - type: CallPerformance
        count: 100
  - start: 120
    scenarios:
      - type: CallPerformance
        count: 200
  - start: 240
    scenarios:
      - type: CallPerformance
        count: 300
  - start: 360
    scenarios:
      - type: CallPerformance
        count: 400
  - start: 480
    scenarios:
      - type: CallPerformance
        count: 500
  - start: 600
    scenarios:
      - type: CallPerformance
        count: 600
  - start: 720
    scenarios:
      - type: CallPerformance
        count: 700
  - start: 840
    scenarios:
      - type: CallPerformance
        count: 800
  - start: 960
    scenarios:
      - type: CallPerformance
        count: 900
  - start: 1080
    scenarios:
      - type: CallPerformance
        count: 1000
  - start: 1200
    scenarios:
      - type: CallPerformance
        count: 1100
  - start: 1320
    scenarios:
      - type: CallPerformance
        count: 1200
  - start: 1440
    scenarios:
      - type: CallPerformance
        count: 1300
  - start: 1560
    scenarios:
      - type: CallPerformance
        count: 1400
  - start: 1680
    scenarios:
      - type: CallPerformance
        count: 1500
  - start: 1800
    scenarios:
      - type: CallPerformance
        count: 1600
  - start: 1920
    scenarios:
      - type: CallPerformance
        count: 1700
  - start: 2040
    scenarios:
      - type: CallPerformance
        count: 1800
  - start: 2160
    scenarios:
      - type: CallPerformance
        count: 1900
  - start: 2280
    scenarios:
      - type: CallPerformance
        count: 2000
  - start: 2400
    scenarios:
      - type: CallPerformance
        count: 2100
  - start: 2520
    scenarios:
      - type: CallPerformance
        count: 2200
  - start: 2640
    scenarios:
      - type: CallPerformance
        count: 2300
  - start: 2760
    scenarios:
      - type: CallPerformance
        count: 2400
  - start: 2880
    scenarios:
      - type: CallPerformance
        count: 2500
  - start: 3000
    scenarios:
      - type: CallPerformance
        count: 2600
  - start: 3120
    scenarios:
      - type: CallPerformance
        count: 2700
  - start: 3240
    scenarios:
      - type: CallPerformance
        count: 2800
  - start: 3360
    scenarios:
      - type: CallPerformance
        count: 2900
  - start: 3480
    scenarios:
      - type: CallPerformance
        count: 3000
  - start: 3600
    scenarios:
      - type: CallPerformance
        count: 3100
  - start: 3720
    scenarios:
      - type: CallPerformance
        count: 3200
  - start: 3840
    scenarios:
      - type: CallPerformance
        count: 3300
  - start: 3960
    scenarios:
      - type: CallPerformance
        count: 3400
  - start: 4080
    scenarios:
      - type: CallPerformance
        count: 3500
  - start: 4200
    scenarios:
      - type: CallPerformance
        count: 3600
  - start: 4320
    scenarios:
      - type: CallPerformance
        count: 3700
  - start: 4440
    scenarios:
      - type: CallPerformance
        count: 3800
  - start: 4560
    scenarios:
      - type: CallPerformance
        count: 3900
  - start: 4680
    scenarios:
      - type: CallPerformance
        count: 4000
  - start: 4800
    scenarios:
      - type: CallPerformance
        count: 4100
  - start: 4920
    scenarios:
      - type: CallPerformance
        count: 4200
  - start: 5040
    scenarios:
      - type: CallPerformance
        count: 4300
  - start: 5160
    scenarios:
      - type: CallPerformance
        count: 4400
  - start: 5280
    scenarios:
      - type: CallPerformance
        count: 4500
  - start: 5400
    scenarios:
      - type: CallPerformance
        count: 4600
  - start: 5520
    scenarios:
      - type: CallPerformance
        count: 4700
  - start: 5640
    scenarios:
      - type: CallPerformance
        count: 4800
  - start: 5760
    scenarios:
      - type: CallPerformance
        count: 4900
  - start: 5880
    scenarios:
      - type: CallPerformance
        count: 5000
  - start: 6000
    scenarios:
      - type: CallPerformance
        count: 5100
  - start: 6120
    scenarios:
      - type: CallPerformance
        count: 5200
  - start: 6240
    scenarios:
      - type: CallPerformance
        count: 5300
  - start: 6360
    scenarios:
      - type: CallPerformance
        count: 5400
  - start: 6480
    scenarios:
      - type: CallPerformance
        count: 5500
  - start: 6600
    scenarios:
      - type: CallPerformance
        count: 5600
  - start: 6720
    scenarios:
      - type: CallPerformance
        count: 5700
  - start: 6840
    scenarios:
      - type: CallPerformance
        count: 5800
  - start: 6960
    scenarios:
      - type: CallPerformance
        count: 5900
  - start: 7080
    scenarios:
      - type: CallPerformance
        count: 6000
  - start: 7200
    scenarios:
      - type: CallPerformance
        count: 6100
  - start: 7320
    scenarios:
      - type: CallPerformance
        count: 6200
  - start: 7440
    scenarios:
      - type: CallPerformance
        count: 6300
  - start: 7560
    scenarios:
      - type: CallPerformance
        count: 6400
  - start: 7680
    scenarios:
      - type: CallPerformance
        count: 6500
  - start: 7800
    scenarios:
      - type: CallPerformance
        count: 6600
  - start: 7920
    scenarios:
      - type: CallPerformance
        count: 6700
  - start: 8040
    scenarios:
      - type: CallPerformance
        count: 6800
  - start: 8160
    scenarios:
      - type: CallPerformance
        count: 6900
  - start: 8280
    scenarios:
      - type: CallPerformance
        count: 7000
  - start: 8400
    scenarios:
      - type: CallPerformance
        count: 7100
  - start: 8520
    scenarios:
      - type: CallPerformance
        count: 7200
end: 8640
