---
threadCount: 8
summary: ./logs/summary.log
timeouts:
  logFile: ./logs/timeouts.log
  samplingPeriod: 1000
profile:
  - start: 0
    scenarios:
      - type: CallPerformance
        count: 300
  - start: 120000
    scenarios:
      - type: CallPerformance
        count: 600
  - start: 240000
    scenarios:
      - type: CallPerformance
        count: 900
  - start: 360000
    scenarios:
      - type: CallPerformance
        count: 1200
  - start: 480000
    scenarios:
      - type: CallPerformance
        count: 1500
  - start: 600000
    scenarios:
      - type: CallPerformance
        count: 1800
  - start: 720000
    scenarios:
      - type: CallPerformance
        count: 2100
  - start: 840000
    scenarios:
      - type: CallPerformance
        count: 2400
  - start: 960000
    scenarios:
      - type: CallPerformance
        count: 2700
  - start: 1080000
    scenarios:
      - type: CallPerformance
        count: 3000
  - start: 1200000
    scenarios:
      - type: CallPerformance
        count: 3300
  - start: 1320000
    scenarios:
      - type: CallPerformance
        count: 3600
  - start: 1440000
    scenarios:
      - type: CallPerformance
        count: 3900
  - start: 1560000
    scenarios:
      - type: CallPerformance
        count: 4200
  - start: 1680000
    scenarios:
      - type: CallPerformance
        count: 4500
  - start: 1800000
    scenarios:
      - type: CallPerformance
        count: 4800
  - start: 1920000
    scenarios:
      - type: CallPerformance
        count: 5100
  - start: 2040000
    scenarios:
      - type: CallPerformance
        count: 5400
  - start: 2160000
    scenarios:
      - type: CallPerformance
        count: 5700
  - start: 2280000
    scenarios:
      - type: CallPerformance
        count: 6000
  - start: 2400000
    scenarios:
      - type: CallPerformance
        count: 6300
  - start: 2520000
    scenarios:
      - type: CallPerformance
        count: 6600
  - start: 2640000
    scenarios:
      - type: CallPerformance
        count: 6900
  - start: 2760000
    scenarios:
      - type: CallPerformance
        count: 7200
  - start: 2880000
    scenarios:
      - type: CallPerformance
        count: 7500
  - start: 3000000
    scenarios:
      - type: CallPerformance
        count: 7800
  - start: 3120000
    scenarios:
      - type: CallPerformance
        count: 8100
  - start: 3240000
    scenarios:
      - type: CallPerformance
        count: 8400
  - start: 3360000
    scenarios:
      - type: CallPerformance
        count: 8700
  - start: 3480000
    scenarios:
      - type: CallPerformance
        count: 9000
  - start: 3600000
    scenarios:
      - type: CallPerformance
        count: 9300
  - start: 3720000
    scenarios:
      - type: CallPerformance
        count: 9600
  - start: 3840000
    scenarios:
      - type: CallPerformance
        count: 9900
  - start: 3960000
    scenarios:
      - type: CallPerformance
        count: 10200
  - start: 4080000
    scenarios:
      - type: CallPerformance
        count: 10500
  - start: 4200000
    scenarios:
      - type: CallPerformance
        count: 10800
  - start: 4320000
    scenarios:
      - type: CallPerformance
        count: 11100
  - start: 4440000
    scenarios:
      - type: CallPerformance
        count: 11400
  - start: 4560000
    scenarios:
      - type: CallPerformance
        count: 11700
  - start: 4680000
    scenarios:
      - type: CallPerformance
        count: 12000
  - start: 4800000
    scenarios:
      - type: CallPerformance
        count: 12300
  - start: 4920000
    scenarios:
      - type: CallPerformance
        count: 12600
  - start: 5040000
    scenarios:
      - type: CallPerformance
        count: 12900
  - start: 5160000
    scenarios:
      - type: CallPerformance
        count: 13200
  - start: 5280000
    scenarios:
      - type: CallPerformance
        count: 13500
  - start: 5400000
    scenarios:
      - type: CallPerformance
        count: 13800
  - start: 5520000
    scenarios:
      - type: CallPerformance
        count: 14100
  - start: 5640000
    scenarios:
      - type: CallPerformance
        count: 14400
  - start: 5760000
    scenarios:
      - type: CallPerformance
        count: 14700
  - start: 5880000
    scenarios:
      - type: CallPerformance
        count: 15000
  - start: 6000000
    scenarios:
      - type: CallPerformance
        count: 15300
  - start: 6120000
    scenarios:
      - type: CallPerformance
        count: 15600
  - start: 6240000
    scenarios:
      - type: CallPerformance
        count: 15900
  - start: 6360000
    scenarios:
      - type: CallPerformance
        count: 16200
  - start: 6480000
    scenarios:
      - type: CallPerformance
        count: 16500
  - start: 6600000
    scenarios:
      - type: CallPerformance
        count: 16800
  - start: 6720000
    scenarios:
      - type: CallPerformance
        count: 17100
  - start: 6840000
    scenarios:
      - type: CallPerformance
        count: 17400
  - start: 6960000
    scenarios:
      - type: CallPerformance
        count: 17700
  - start: 7080000
    scenarios:
      - type: CallPerformance
        count: 18000
  - start: 7200000
    scenarios:
      - type: CallPerformance
        count: 18300
  - start: 7320000
    scenarios:
      - type: CallPerformance
        count: 18600
  - start: 7440000
    scenarios:
      - type: CallPerformance
        count: 18900
  - start: 7560000
    scenarios:
      - type: CallPerformance
        count: 19200
  - start: 7680000
    scenarios:
      - type: CallPerformance
        count: 19500
  - start: 7800000
    scenarios:
      - type: CallPerformance
        count: 19800
  - start: 7920000
    scenarios:
      - type: CallPerformance
        count: 20100
  - start: 8040000
    scenarios:
      - type: CallPerformance
        count: 20400
  - start: 8160000
    scenarios:
      - type: CallPerformance
        count: 20700
  - start: 8280000
    scenarios:
      - type: CallPerformance
        count: 21000
  - start: 8400000
    scenarios:
      - type: CallPerformance
        count: 21300
  - start: 8520000
    scenarios:
      - type: CallPerformance
        count: 21600
end: 8640000
