---
description: "Simple config which spawns one CallPerformance scenario and ends after 10 seconds"
threadCount: 1
summary: ./logs/summary.log
statistics:
  logFile: ./logs/statistics.log
  samplingPeriod: 1000
profile:
  burstLimit: 10
  end: 10
  flow:
    - start: 0
      scenarios:
        - type: CallPerformance
          count: 1
