---
description: "Stress test"
threadCount: 8
summary: ./logs/summary.log
statistics:
  logFile: ./logs/statistics.log
  samplingPeriod: 1000
profile:
  burstLimit: 1000
  end: 8640
  flow:
    - start: 0
      scenarios:
        - type: CallPerformance
          count: 20000
    - start: 600
      scenarios:
        - type: CallPerformance
          count: 100
