---
description: "Stress test"
threadCount: 8
summary: ./logs/summary.log
statistics:
  logFile: ./logs/statistics.log
  samplingPeriod: 1000
profile:
  burstLimit: 500
  end: 8640
  flow:
    - start: 0
      scenarios:
        - type: CallPerformance
          count: 50000
    - start: 600
      scenarios:
        - type: CallPerformance
          count: 100
    - start: 2880
      scenarios:
        - type: CallPerformance
          count: 50000
    - start: 3480
      scenarios:
        - type: CallPerformance
          count: 100
    - start: 5760
      scenarios:
        - type: CallPerformance
          count: 50000
    - start: 6360
      scenarios:
        - type: CallPerformance
          count: 100
